'use client'

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react'

export type Language = 'ro' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const translations = {
  ro: {
    // Hero Section
    'hero.badge': 'Import Auto Personalizat din Europa',
    'hero.title': 'Import auto',
    'hero.title.highlight': 'simplu și sigur.',
    'hero.subtitle': 'Găsim, verificăm și livrăm mașina dorită din Europa.',
    'hero.cta.primary': 'Vreau Mașina Mea',
    'hero.cta.secondary': 'Calculator Cost',
    'hero.cta.tertiary': 'Vezi Licitațiile Live',
    'hero.features.no_hidden_costs': 'Calculator transparent',
    'hero.features.full_warranty': 'Garanție 12 luni inclusă',
    'hero.features.fast_delivery': 'Livrare cu RAR efectuat',
    'hero.expert': 'Verificat & Garantat',
    'hero.expert.subtitle': '100% transparent',

    // International Auctions Section
    'international_auctions.title': 'Acces Direct la Licitațiile Internaționale',
    'international_auctions.subtitle': 'Importăm din cele mai mari piețe auto din lume pentru a-ți oferi prețurile cele mai bune și selecția cea mai mare',
    'international_auctions.countries.title': 'Piețe de Import',
    'international_auctions.platforms.title': 'Platforme Partenere',
    'international_auctions.benefits.title': 'Avantajele Noastre',
    'international_auctions.benefits.better_prices': 'Prețuri cu 20-30% mai mici',
    'international_auctions.benefits.huge_selection': 'Selecție de peste 100,000 vehicule',
    'international_auctions.benefits.direct_access': 'Acces direct la licitații live',
    'international_auctions.benefits.quality_control': 'Verificări și inspecții complete',
    'international_auctions.countries.usa': 'SUA',
    'international_auctions.countries.eu': 'Uniunea Europeană',
    'international_auctions.cta': 'Vezi Licitațiile Live',

    // How It Works Section
    'how_it_works.title': 'Cum aducem mașina dorită în doar 4 pași.',
    'how_it_works.subtitle': 'Procesul nostru simplu în 4 pași pentru a-ți importa mașina de vis',
    'how_it_works.step1.title': 'Consultație',
    'how_it_works.step1.description': 'Discutăm despre preferințele tale și bugetul disponibil',
    'how_it_works.step2.title': 'Căutare',
    'how_it_works.step2.description': 'Analizăm mii de mașini de pe platformele europene.',
    'how_it_works.step3.title': 'Import',
    'how_it_works.step3.description': 'Gestionăm toate formalitățile de import și transport',
    'how_it_works.step4.title': 'Livrare',
    'how_it_works.step4.description': 'Îți livrăm mașina direct la adresa ta',

    // Why Choose Us Section
    'why_choose.title': 'Import auto fără riscuri',
    'why_choose.subtitle': 'Partenerii tăi de încredere pentru import auto din Europa. Îți oferim servicii complete și transparente pentru a-ți aduce mașina perfectă.',
    'why_choose.warranty.title': 'Garanție 12 luni',
    'why_choose.warranty.description': 'Pentru liniștea ta după livrare.',
    'why_choose.report.title': 'Raport complet înainte de cumpărare',
    'why_choose.report.description': 'Primești istoricul mașinii înainte de achiziție.',
    'why_choose.delivery.title': 'Transport organizat de noi',
    'why_choose.delivery.description': 'Mașina ajunge în siguranță în România.',
    'why_choose.registration.title': 'RAR și înmatriculare',
    'why_choose.registration.description': 'Nu pierzi timp cu birocrația.',

    // Featured Cars Section
    'featured_cars.title': 'Mașini disponibile',
    'featured_cars.subtitle': '4 mașini disponibile acum — stoc limitat, actualizat săptămânal.',
    'featured_cars.badge.premium': 'Premium',
    'featured_cars.badge.luxury': 'Luxury',
    'featured_cars.badge.performance': 'Performance',
    'featured_cars.details_button': 'Detalii',

    // Cost Estimator Section
    'cost_estimator.title': 'Calculează Costurile Exact',
    'cost_estimator.subtitle': 'Folosește calculatorul nostru avansat pentru a obține o estimare precisă a costurilor pentru importul mașinii tale. Include toate taxele, transportul și comisioanele.',
    'cost_estimator.feature1': 'Calculator cu 2 variante: Fără TVA și Cu TVA',
    'cost_estimator.feature2': 'Calcul automat al avansului necesar (20%)',
    'cost_estimator.feature3': 'Rezultate în timp real, fără surprize',
    'cost_estimator.cta': 'Calculator Cost',

    // Warranty Section
    'warranty.title': 'Garanție Completă de 12 Luni',
    'warranty.subtitle': 'Investești în mașina ta cu încredere totală. Fiecare vehicul importat vine cu garanția noastră extinsă pentru liniștea ta deplină.',
    'warranty.complete_protection.title': 'Protecție Completă',
    'warranty.complete_protection.description': 'Acoperim toate problemele mecanice și electrice care pot apărea în primul an de la import, fără excepții.',
    'warranty.quality_service.title': 'Service de Calitate',
    'warranty.quality_service.description': 'Colaborăm cu service-uri autorizate pentru a-ți asigura reparații profesionale și mentenanță de încredere.',
    'warranty.dedicated_support.title': 'Suport Dedicat',
    'warranty.dedicated_support.description': 'Echipa noastră îți oferă consultanță și asistență pe toată perioada garanției pentru liniștea ta.',
    'warranty.what_includes.title': 'Ce Include Garanția Noastră?',
    'warranty.what_includes.mechanical': 'Componente mecanice principale',
    'warranty.what_includes.electrical': 'Sisteme electrice și electronice',
    'warranty.what_includes.safety': 'Elemente de siguranță și confort',
    'warranty.what_includes.support': 'Support tehnic și consultanță',
    'warranty.months': 'Luni Garanție',
    'warranty.months_description': 'Cea mai extinsă garanție din industrie pentru mașini importate',
    'warranty.questions.title': 'Ai Întrebări Despre Garanție?',
    'warranty.questions.subtitle': 'Echipa noastră de specialiști îți explică în detaliu toate beneficiile garanției extended și cum te protejează investiția ta.',
    'warranty.cta.primary': 'Vreau Mașina',
    'warranty.cta.secondary': 'Întreabă-ne',

    // Available Cars Section
    'cars.title': 'Mașini Disponibile',
    'cars.subtitle': 'Descoperă mașinile premium din stocul nostru și cele în consignație',
    'cars.count': 'mașini disponibile',
    'cars.year': 'An',
    'cars.mileage': 'Kilometraj',
    'cars.fuel': 'Combustibil',
    'cars.engine': 'Motor',
    'cars.transmission': 'Transmisie',
    'cars.price': 'Preț',
    'cars.details': 'Vezi Detalii',

    // Exclusivity Section
    'exclusivity.badge': 'Locuri limitate —',
    'exclusivity.title': 'Acceptăm doar un număr limitat de comenzi.',
    'exclusivity.subtitle': 'Lucrăm cu un număr mic de clienți pentru că fiecare comandă primește atenție personală, de la căutare până la livrare.',
    'exclusivity.reserved': 'Locul tău a fost rezervat!',
    'exclusivity.contact_soon': 'Te contactăm în curând la',
    'exclusivity.email_placeholder': 'Adresa ta de email',
    'exclusivity.cta': 'Rezervă locul tău gratuit →',

    // FAQ Section
    'faq.title': 'Întrebări Frecvente',
    'faq.subtitle': 'Răspunsuri la cele mai comune întrebări despre serviciul nostru de import auto personalizat',
    'faq.q1.question': 'Cum funcționează importul auto personalizat?',
    'faq.q1.answer': 'Configurezi exact mașina dorită (marca, model, culoare, dotări) prin platforma noastră. Noi o căutăm și achiziționăm din licitațiile internaționale (OpenLane, Auto1), apoi ți-o aducem în România cu toate formalitățile făcute.',
    'faq.q2.question': 'Ce platforme de licitații utilizați?',
    'faq.q2.answer': 'Colaborăm cu OpenLane.eu pentru licitații auto și Auto1.com pentru piața europeană. Acestea ne oferă acces la peste 100,000 de vehicule din licitații live.',
    'faq.q3.question': 'Cât costă să îmi import o mașină la comandă?',
    'faq.q3.answer': 'Folosește calculatorul nostru pentru o estimare exactă. Includem toate costurile: prețul mașinii, transport, înmatriculare RAR, plus garanția noastră de 12 luni. Fără surprize!',
    'faq.q4.question': 'Ce garanție oferiti și ce include?',
    'faq.q4.answer': 'Oferim garanție de 12 luni, cea mai extinsă din România pentru mașini importate. Acoperă componente mecanice, sisteme electrice, elemente de siguranță, plus suport tehnic și consultanță.',
    'faq.q5.question': 'Vă ocupați și de înmatricularea la RAR?',
    'faq.q5.answer': 'Absolut! Serviciul nostru all-inclusive include toate formalitățile RAR. Îți livrăm mașina cu numerele puse și gata de condus, plus ITP-ul făcut.',

    // Testimonials Section
    'testimonials.title': 'Ce Spun Clienții Noștri',
    'testimonials.subtitle': 'Experiențele reale ale clienților noștri mulțumiți',
    'testimonials.review1': 'Serviciu excelent! Mi-au găsit exact BMW-ul pe care îl căutam și au gestionat totul profesional.',
    'testimonials.review2': 'Transparent, rapid și eficient. Economisesc mult față de piața locală și mașina e în stare perfectă.',
    'testimonials.review3': 'Echipa Automode m-a ajutat să îmi import Mercedes-ul de vis. Procesul a fost simplu și fără probleme.',

    // WhatsApp
    'whatsapp.tooltip': 'Scrie-ne pe WhatsApp',

    // Header Navigation
    'header.nav.calculator': 'Calculator Cost',
    'header.nav.order_car': 'Comandă Mașină',
    'header.nav.send_openlane': 'Trimite Link',
    'header.nav.masini_la_comanda': 'Mașini la Comandă',
    'header.nav.stoc': 'Stoc',
    'header.nav.navigation': 'Navigație',
    'header.user.welcome': 'Bun venit!',

    // Header User Menu
    'header.user.my_account': 'Contul meu',
    'header.user.sign_out': 'Deconectează-te',
    'header.user.sign_in': 'Conectează-te',
    'header.user.create_account': 'Creează Cont',
    'header.user.administrator': 'Administrator',

    // Breadcrumbs
    'breadcrumbs.home': 'Acasă',
    'breadcrumbs.masini_la_comanda': 'Mașini la Comandă',
    'breadcrumbs.calculator': 'Calculator Import',
    'breadcrumbs.stoc': 'Stoc Mașini',
    'breadcrumbs.dashboard': 'Dashboard',
    'breadcrumbs.cereri': 'Cereri',
    'breadcrumbs.analitice': 'Analitice',
    'breadcrumbs.confidentialitate': 'Politica de Confidențialitate',
    'breadcrumbs.cookies': 'Politica de Cookies',
    'breadcrumbs.gdpr': 'GDPR',

    // Footer
    'footer.company_description': 'Partenerul tău de încredere pentru importul de vehicule premium din Europa. Ne ocupăm de tot, de la selecție la livrare, transformând mașina ta de vis în realitate.',
    'footer.services': 'Servicii',
    'footer.order_car': 'Comandă Mașină',
    'footer.cost_calculator': 'Calculator Cost',
    'footer.legal': 'Legal',
    'footer.terms_conditions': 'Termeni și Condiții',
    'footer.privacy_policy': 'Politica de Confidențialitate',
    'footer.cookies_policy': 'Politica de Cookie-uri',
    'footer.copyright': 'Automode SRL',

    // Dashboard Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.car_requests': 'Cereri Mașini',
    'sidebar.calculator': 'Calculator Cost',
    'sidebar.contracts': 'Contracte',
    'sidebar.logout': 'Ieșire',

    // Dashboard Page
    'dashboard.welcome': 'Bună ziua',
    'dashboard.subtitle': 'Bine ai venit în dashboard-ul tău Automode',
    'dashboard.stats.active_requests': 'Cereri Active',
    'dashboard.stats.offers_received': 'Oferte Primite',
    'dashboard.stats.contracts': 'Contracte',
    'dashboard.account_info': 'Informații Cont',
    'dashboard.account_info.name': 'Nume',
    'dashboard.account_info.email': 'Email',
    'dashboard.account_info.phone': 'Telefon',
    'dashboard.account_info.member_since': 'Membru din',
    'dashboard.account_info.not_set': 'Nu este setat',
    'dashboard.recent_activity': 'Activitate Recentă',
    'dashboard.recent_activity.contract': 'Contract',
    'dashboard.recent_activity.client': 'Client',
    'dashboard.recent_activity.contract_date': 'Data contract',
    'dashboard.recent_activity.created': 'Creat',
    'dashboard.recent_activity.status.signed': 'Semnat',
    'dashboard.recent_activity.status.draft': 'Ciornă',
    'dashboard.recent_activity.no_activity': 'Nu există activitate recentă',
    'dashboard.recent_activity.contracts_appear_here': 'Contractele tale vor apărea aici',

    // Calculator Page
    'calculator.title': 'Calculator Cost Import',
    'calculator.subtitle': 'Calculează costurile exacte pentru importul mașinii tale din Europa',

    // Contracts Page
    'contracts.title': 'Contractele Mele',
    'contracts.subtitle': 'Vizualizează și gestionează contractele tale',

    // Car Requests Page
    'car_requests.new_order': 'Comandă Mașină Nouă',
    'car_requests.form_description': 'Completează formularul pentru a crea o cerere nouă',
    'car_requests.year': 'An',
    'car_requests.max_budget': 'Buget maxim',
    'car_requests.fuel_type': 'Combustibil',
    'car_requests.additional_requirements': 'Cerințe suplimentare',
    'car_requests.created_on': 'Creată pe',
    'car_requests.not_specified': 'Nu specificat',

    // Calculator Component
    'calc.title': 'Calculator Cost Import',
    'calc.tab.without_vat': 'Fără TVA',
    'calc.tab.with_vat': 'Cu TVA',
    'calc.price_label': 'Preț mașină (€)',
    'calc.price_placeholder': 'Introduceti pretul masinii',
    'calc.openlane_taxes': 'Taxe OpenLane',
    'calc.transport_label': 'Transport (€)',
    'calc.transport_placeholder': 'Introduceti costul transportului',
    'calc.warranty': 'Garanție',
    'calc.commission': 'Comision',
    'calc.vat': 'TVA (21%)',
    'calc.total': 'Total',
    'calc.advance': 'Avans necesar (20%)',

    // Contracts Page Details
    'contracts.loading': 'Se încarcă contractele...',
    'contracts.no_contracts': 'Nu aveți contracte disponibile',
    'contracts.status.draft': 'Ciornă',
    'contracts.status.signed': 'Semnat',
    'contracts.status.sent_to_client': 'Trimis la client',
    'contracts.status.signed_by_client': 'Semnat de client',
    'contracts.status.archived': 'Arhivat',
    'contracts.status.cancelled': 'Anulat',
    'contracts.view_contract': 'Vezi Contract',
    'contracts.sign_contract': 'Semnează Contract',
    'contracts.contract_number': 'Contract',
    'contracts.created': 'Creat',
    'contracts.amount': 'Sumă',

    // Car Selection Form
    'car_form.title': 'Selectează Mașina Dorită',
    'car_form.subtitle': 'Completează detaliile despre mașina pe care o cauți',
    'car_form.make_label': 'Marca *',
    'car_form.make_placeholder': 'Selectează marca...',
    'car_form.model_label': 'Modelul *',
    'car_form.model_placeholder': 'Selectează modelul...',
    'car_form.year_label': 'Anul *',
    'car_form.year_placeholder': 'Selectează anul...',
    'car_form.fuel_type_label': 'Tipul de Combustibil (opțional)',
    'car_form.fuel_type_placeholder': 'Selectează tipul de combustibil...',
    'car_form.transmission_label': 'Tipul de Transmisie (opțional)',
    'car_form.transmission_placeholder': 'Selectează tipul de transmisie...',
    'car_form.max_mileage_label': 'Kilometrajul Maxim (opțional)',
    'car_form.max_mileage_placeholder': 'ex: 150000',
    'car_form.max_mileage_hint': 'în kilometri',
    'car_form.budget_label': 'Buget (EUR) *',
    'car_form.budget_placeholder': 'ex: 25000',
    'car_form.features_label': 'Caracteristici Dorite (opțional)',
    'car_form.features_placeholder': 'Selectează caracteristicile...',
    'car_form.additional_notes_label': 'Note Adiționale (opțional)',
    'car_form.additional_notes_placeholder': 'Detalii suplimentare despre mașina dorită, preferințe speciale...',
    'car_form.submit_button': 'Trimite Cererea',
    'car_form.submitting_button': 'Se trimite...',

    // Car Features
    'car_features.leather': 'Interior din piele',
    'car_features.sunroof': 'Trapă',
    'car_features.navigation': 'Sistem de navigație',
    'car_features.heated_seats': 'Scaune încălzite',
    'car_features.cooled_seats': 'Scaune ventilate',
    'car_features.heated_steering': 'Volan încălzit',
    'car_features.bluetooth': 'Bluetooth',
    'car_features.backup_camera': 'Cameră de mers înapoi',
    'car_features.360_camera': 'Cameră 360°',
    'car_features.cruise_control': 'Cruise control',
    'car_features.adaptive_cruise': 'Cruise control adaptiv',
    'car_features.keyless': 'Pornire fără cheie',
    'car_features.keyless_entry': 'Acces fără cheie',
    'car_features.premium_audio': 'Sistem audio premium',
    'car_features.xenon': 'Faruri Xenon/LED',
    'car_features.matrix_led': 'Faruri Matrix LED',
    'car_features.parking_sensors': 'Senzori de parcare',
    'car_features.auto_park': 'Parcare automată',
    'car_features.climate_control': 'Climatizare automată',
    'car_features.dual_zone_climate': 'Climatizare bi-zonă',
    'car_features.tri_zone_climate': 'Climatizare tri-zonă',
    'car_features.lane_assist': 'Asistent de bandă',
    'car_features.blind_spot': 'Monitor unghi mort',
    'car_features.collision_warning': 'Avertizare coliziune',
    'car_features.emergency_brake': 'Frânare de urgență',
    'car_features.traffic_sign': 'Recunoaștere indicatoare',
    'car_features.wireless_charging': 'Încărcare wireless',
    'car_features.apple_carplay': 'Apple CarPlay',
    'car_features.android_auto': 'Android Auto',
    'car_features.heads_up_display': 'Head-up Display',
    'car_features.panoramic_roof': 'Plafonul panoramic',
    'car_features.electric_seats': 'Scaune electrice',
    'car_features.memory_seats': 'Scaune cu memorie',
    'car_features.massage_seats': 'Scaune cu masaj',
    'car_features.sport_suspension': 'Suspensie sport',
    'car_features.air_suspension': 'Suspensie pneumatică',
    'car_features.awd': 'Tracțiune integrală',
    'car_features.sport_mode': 'Moduri de conducere',
    'car_features.start_stop': 'Sistem Start-Stop',
    'car_features.eco_mode': 'Mod Eco',
    'car_features.night_vision': 'Vedere nocturnă',
    'car_features.ambient_lighting': 'Iluminare ambientală',

    // Fuel Types
    'fuel_types.benzina': 'Benzină',
    'fuel_types.motorina': 'Motorină',
    'fuel_types.hybrid': 'Hibrid',
    'fuel_types.electric': 'Electric',
    'fuel_types.gpl': 'GPL',
    'fuel_types.cng': 'CNG',
    'fuel_types.mild_hybrid': 'Mild Hybrid',
    'fuel_types.plug_in_hybrid': 'Plug-in Hybrid',
    'fuel_types.hydrogen': 'Hidrogen',
    'fuel_types.ethanol': 'Etanol',
    'fuel_types.lpg': 'LPG',
    'fuel_types.flex_fuel': 'Flex Fuel',
    'fuel_types.bi_fuel': 'Bi-Fuel',
    'fuel_types.range_extender': 'Range Extender',

    // Transmission Types
    'transmission.manuala': 'Manuală',
    'transmission.automata': 'Automată',
    'transmission.semiautomata': 'Semiautomată',
    'transmission.cvt': 'CVT',
    'transmission.dsg': 'DSG',
    'transmission.tiptronic': 'Tiptronic',
    'transmission.multitronic': 'Multitronic',
    'transmission.s_tronic': 'S-Tronic',
    'transmission.pdk': 'PDK',
    'transmission.zf_8hp': 'ZF 8HP',
    'transmission.torque_converter': 'Torque Converter',
    'transmission.dual_clutch': 'Dual Clutch',
    'transmission.single_speed': 'Single Speed (Electric)',
    'transmission.e_cvt': 'e-CVT',
    'transmission.amt': 'AMT',
    'transmission.imt': 'iMT',

    // Validation Messages
    'validation.select_make': 'Selectează marca',
    'validation.select_model': 'Selectează modelul',
    'validation.year_after_1985': 'Anul trebuie să fie după 1985',
    'validation.year_not_future': 'Anul nu poate fi în viitor',
    'validation.budget_min': 'Bugetul minim este €1,000',
    'validation.budget_max': 'Bugetul maxim este €500,000',

    // Toast Messages
    'toast.login_required': 'Trebuie să fii conectat pentru a trimite o cerere.',
    'toast.profile_error': 'Nu am putut accesa informațiile de profil.',
    'toast.database_error': 'Eroare bază de date',
    'toast.email_failed': 'Cererea a fost salvată, dar notificarea email a eșuat.',
    'toast.request_success': 'Cererea ta a fost trimisă cu succes! O vei găsi în lista de cereri.',
    'toast.general_error': 'A apărut o eroare. Te rugăm să încerci din nou.',

    // Consignatie Section
    'consignatie.title': 'Consignație Auto',
    'consignatie.subtitle': 'Îți vindem mașina în siguranță și la cel mai bun preț',
    'consignatie.description': 'Pune-ți mașina în consignația noastră și lasă-ne să o vindem pentru tine. Ne ocupăm de tot procesul de vânzare, de la promovare până la finalizarea tranzacției.',
    'consignatie.benefit1.title': 'Evaluare Profesională',
    'consignatie.benefit1.description': 'Evaluăm corect mașina ta și stabilim cel mai bun preț de vânzare pe piață',
    'consignatie.benefit2.title': 'Marketing Complet',
    'consignatie.benefit2.description': 'Promovăm mașina ta pe toate platformele relevante și în rețeaua noastră de cumpărători',
    'consignatie.benefit3.title': 'Documentație Completă',
    'consignatie.benefit3.description': 'Ne ocupăm de toate actele și formalitățile necesare pentru vânzare',
    'consignatie.benefit4.title': 'Plata Garantată',
    'consignatie.benefit4.description': 'Primești banii imediat după vânzare, fără riscuri sau întârzieri',
    'consignatie.cta': 'Pune Mașina în Consignație',
    'consignatie.contact': 'Contactează-ne pentru Evaluare',

    // Progress Tracking
    'progress.title': 'Progresul Importului Auto',
    'progress.stages_completed': '{{completed}} din {{total}} etape finalizate',
    'progress.percent_complete': '{{percent}}% complet',
    'progress.current_stage': 'Etapa curentă: {{stage}}',
    'progress.notification_text': 'Vei fi notificat când această etapă se finalizează și trecem la următoarea.',
    'progress.stages.requested': 'Cerere trimisă',
    'progress.stages.requested_desc': 'Cererea ta de import auto a fost trimisă',
    'progress.stages.searching': 'Căutare activă',
    'progress.stages.searching_desc': 'Căutăm activ vehiculul dorit de tine',
    'progress.stages.found': 'Mașină găsită',
    'progress.stages.found_desc': 'Potrivire perfectă găsită! Detaliile vehiculului vor fi împărtășite',
    'progress.stages.auction_time': 'Timp de licitație',
    'progress.stages.auction_time_desc': 'Mașina este la licitație - rezultatul va fi comunicat în curând',
    'progress.stages.auction_won': 'Licitație câștigată',
    'progress.stages.auction_won_desc': 'Felicitări! Am câștigat licitația pentru mașina ta',
    'progress.stages.auction_lost': 'Achizitie Esuata (pret depasit)',
    'progress.stages.auction_lost_desc': 'Din păcate prețul a depășit bugetul stabilit',
    'progress.stages.purchase_failed': 'Achizitie Esuata (pret depasit)',
    'progress.stages.purchase_failed_desc': 'Din păcate prețul a depășit bugetul stabilit',
    'progress.stages.purchased': 'Cumpărată',
    'progress.stages.purchased_desc': 'Vehicul cumpărat! Plată confirmată și procesată',
    'progress.stages.in_transit': 'În transport',
    'progress.stages.in_transit_desc': 'Vehiculul este transportat în România',
    'progress.stages.delivered': 'Livrată',
    'progress.stages.delivered_desc': 'Vehicul gata pentru ridicare sau livrare la domiciliu',
    'progress.status.in_progress': 'În progres',
    'progress.status.completed': 'Finalizat',
    'progress.status.delayed': 'Întârziere',
    'progress.date.completed': 'Finalizat: {{date}}',
    'progress.date.estimated': 'Estimat: {{date}}',
    'progress.date.today': 'Astăzi',
    'progress.date.tomorrow': 'Mâine',
    'progress.date.in_days': 'în {{days}} zile',
    'progress.date.yesterday': 'Ieri',
    'progress.date.days_ago': 'acum {{days}} zile',
    'progress.last_updated': 'Ultima actualizare',

    // Notifications
    'notifications.title': 'Notificări',
    'notifications.mark_all_read': 'Marchează toate ca citite',
    'notifications.no_notifications': 'Nu ai notificări noi',
    'notifications.no_notifications_desc': 'Îți vom arăta aici actualizări despre cererile tale.',

    // Onboarding
    'onboarding.welcome': 'Bun venit',
    'onboarding.skip': 'Omite ghidarea',
    'onboarding.next': 'Următorul',
    'onboarding.previous': 'Înapoi',
    'onboarding.finish': 'Să începem!',
    'onboarding.step_of': 'Pasul {{current}} din {{total}}',

    // Stoc Page
    'stoc.title': 'Stocul Nostru',
    'stoc.subtitle': 'Descoperă mașinile disponibile în stocul nostru. Toate vehiculele sunt verificate și pregătite pentru livrare.',
    'stoc.empty.title': 'Nu există mașini în stoc momentan',
    'stoc.empty.subtitle': 'Verifică din nou în curând pentru noi vehicule adăugate.',
    'stoc.spec.year': 'An',
    'stoc.spec.km': 'Km',
    'stoc.spec.fuel': 'Combustibil',
    'stoc.spec.engine': 'Motor',
    'stoc.spec.transmission': 'Transmisie',
    'stoc.spec.equipment': 'Echipare',
    'stoc.price': 'Preț',
    'stoc.view_details': 'Vezi Detalii',
    'stoc.banner.text': 'Nu găsești ce cauți? Comandăm orice mașină din Europa în 2-3 săptămâni.',
    'stoc.banner.cta': 'Vreau Mașina Mea',

    // Stoc Detail Page
    'stoc_detail.back': 'Înapoi la Stoc',
    'stoc_detail.warranty.title': 'Garanție',
    'stoc_detail.warranty.months': 'Luni',
    'stoc_detail.warranty.description': 'Protecție completă inclusă',
    'stoc_detail.warranty.certified': 'CERTIFICAT',
    'stoc_detail.spec.year': 'An',
    'stoc_detail.spec.km': 'Kilometri',
    'stoc_detail.spec.fuel': 'Combustibil',
    'stoc_detail.spec.engine': 'Motor',
    'stoc_detail.spec.power': 'Putere',
    'stoc_detail.spec.transmission': 'Transmisie',
    'stoc_detail.spec.co2': 'Emisii CO2',
    'stoc_detail.spec.equipment': 'Echipare',
    'stoc_detail.spec.vin': 'VIN',
    'stoc_detail.spec.registration': 'Înmatriculare',
    'stoc_detail.price': 'Preț:',
    'stoc_detail.contact': 'Contactează-ne: 0770852489',
    'stoc_detail.features': 'Dotări',
    'stoc_detail.report.view': 'Vezi Raportul CarVertical',
    'stoc_detail.report.title': 'Raport CarVertical',
    'stoc_detail.report.short': 'Raport CV',
    'stoc_detail.report.download': 'Descarcă',
    'stoc_detail.error': 'Mașina nu a fost găsită',

    // Calculator Page
    'calc_page.title': 'Calculator Cost',
    'calc_page.subtitle': 'Calculează costurile pentru importul mașinii tale',
    'calc_page.tab.without_vat': 'Fără TVA',
    'calc_page.tab.with_vat': 'Cu TVA',
    'calc_page.price_label': 'Preț (EUR)',
    'calc_page.price_placeholder': 'Introdu prețul',
    'calc_page.auction_taxes_label': 'Taxe Licitații (EUR)',
    'calc_page.auction_taxes_hint': 'Prețul este aproximativ deoarece diferă pentru fiecare țară',
    'calc_page.vat_label': 'TVA 21% (EUR)',
    'calc_page.vat_hint': 'TVA se calculează pe baza prețului + taxe OpenLane (21%)',
    'calc_page.transport_label': 'Transport (EUR)',
    'calc_page.commission_label': 'Comision (EUR)',
    'calc_page.total': 'Total:',
    'calc_page.note_prefix': 'Notă:',
    'calc_page.advance_note': 'Dacă doriți să continuați, avansul nostru este de 20% din prima sumă.',
    'calc_page.advance_label': 'Avans necesar (20%):',
    'calc_page.cta.title': 'Gata să Îți Cumperi Mașina de Vis?',
    'calc_page.cta.text': 'Acum că știi costurile exacte, solicită mașina dorită și începe procesul de comandă. Echipa noastră te va ghida pas cu pas spre mașina perfectă.',
    'calc_page.cta.button': 'Vreau această mașină.',
    'calc_page.cta.benefits': '✓ Cont gratuit • ✓ Fără obligații • ✓ Suport personalizat',

    // Car Order Form (multi-step)
    'car_order_form.step1.label': 'Contact',
    'car_order_form.step2.label': 'Preferințe',
    'car_order_form.step3.label': 'Detalii',
    'car_order_form.step4.label': 'Confirmare',
    'car_order_form.full_name_label': 'Nume Complet *',
    'car_order_form.phone_label': 'Telefon *',
    'car_order_form.brand_label': 'Marcă *',
    'car_order_form.brand_placeholder': 'Selectează marca',
    'car_order_form.other_brand': 'Altă marcă',
    'car_order_form.custom_brand_label': 'Specifică Marca *',
    'car_order_form.custom_brand_placeholder': 'Ex: Dacia, Subaru, Mitsubishi',
    'car_order_form.model_label': 'Model *',
    'car_order_form.model_placeholder': 'Ex: Seria 5, E-Class, A6',
    'car_order_form.year_min_label': 'An Fabricație (Minim) *',
    'car_order_form.year_max_label': 'An Fabricație (Maxim)',
    'car_order_form.year_placeholder': 'Selectează anul',
    'car_order_form.fuel_label': 'Tip Combustibil',
    'car_order_form.fuel_placeholder': 'Selectează tipul',
    'car_order_form.transmission_label': 'Transmisie',
    'car_order_form.transmission_placeholder': 'Selectează tipul',
    'car_order_form.fuel.benzina': 'Benzină',
    'car_order_form.fuel.diesel': 'Diesel',
    'car_order_form.fuel.hibrid': 'Hibrid',
    'car_order_form.fuel.electric': 'Electric',
    'car_order_form.fuel.hibrid_plugin': 'Hibrid Plug-in',
    'car_order_form.fuel.any': 'Indiferent',
    'car_order_form.transmission.automatic': 'Automată',
    'car_order_form.transmission.manual': 'Manuală',
    'car_order_form.transmission.any': 'Indiferent',
    'car_order_form.budget_min_label': 'Buget Minim (EUR) *',
    'car_order_form.budget_max_label': 'Buget Maxim (EUR) *',
    'car_order_form.mileage_label': 'Kilometraj Maxim (km)',
    'car_order_form.color_label': 'Culoare Preferată',
    'car_order_form.color_placeholder': 'Ex: Negru, Alb, Gri',
    'car_order_form.requirements_label': 'Cerințe Suplimentare',
    'car_order_form.requirements_placeholder': 'Menționează orice alte cerințe sau preferințe (ex: pachet sport, interior piele, sistem audio premium, etc.)',
    'car_order_form.review_title': 'Verifică Datele Tale:',
    'car_order_form.review.name': 'Nume:',
    'car_order_form.review.email': 'Email:',
    'car_order_form.review.phone': 'Telefon:',
    'car_order_form.review.brand': 'Marcă:',
    'car_order_form.review.model': 'Model:',
    'car_order_form.review.year': 'An:',
    'car_order_form.review.budget': 'Buget:',
    'car_order_form.review.fuel': 'Combustibil:',
    'car_order_form.review.transmission': 'Transmisie:',
    'car_order_form.terms_prefix': 'Accept ',
    'car_order_form.terms_link': 'Politica de Confidențialitate',
    'car_order_form.terms_suffix': ' și sunt de acord ca AutoMode să mă contacteze cu oferte personalizate pentru mașina dorită.',
    'car_order_form.back': 'Înapoi',
    'car_order_form.continue': 'Continuă',
    'car_order_form.submit': 'Trimite Comanda',
    'car_order_form.submitting': 'Se trimite...',
    'car_order_form.success.title': 'Mulțumim pentru comandă!',
    'car_order_form.success.message': 'Am primit cererea ta și echipa noastră te va contacta în curând cu oferte personalizate.',
    'car_order_form.success.back_home': 'Înapoi la Pagina Principală',
    'car_order_form.error': 'A apărut o eroare. Vă rugăm să încercați din nou.',

    // Masini la Comanda Page
    'masini_comanda.title': 'Spune-ne ce mașină vrei. Noi o găsim.',
    'masini_comanda.subtitle': 'Completează în 2 minute — echipa noastră te contactează în maxim 24 de ore cu opțiuni concrete.',
    'masini_comanda.cta.title': 'Ai Întrebări?',
    'masini_comanda.cta.text': 'Echipa noastră este aici să te ajute cu orice nelămurire. Contactează-ne pe WhatsApp pentru consultanță gratuită.',
    'masini_comanda.cta.button': 'WhatsApp',
    'masini_comanda.faq.title': 'Întrebări Frecvente',
    'masini_comanda.faq.q1.question': 'Cât durează procesul de import?',
    'masini_comanda.faq.q1.answer': 'De la momentul plății avansului până la livrarea mașinii la tine acasă durează în medie 2-3 săptămâni. Acest termen include găsirea mașinii potrivite, verificarea tehnică, și transport.',
    'masini_comanda.faq.q2.question': 'Care este avansul necesar?',
    'masini_comanda.faq.q2.answer': 'Solicităm un avans de 20% din prețul total pentru a începe procesul de licitare a mașinii. Restul sumei se plătește după câștigarea licitației în termen de 48 de ore.',
    'masini_comanda.faq.q3.question': 'Ce include garanția de 12 luni?',
    'masini_comanda.faq.q3.answer': 'Garanția acoperă toate componentele mecanice și electrice majore: motor, transmisie, sistem de frânare, suspensie, sistem electric și electronică.',
    'masini_comanda.faq.q4.question': 'Pot vedea mașina înainte să o cumpăr?',
    'masini_comanda.faq.q4.answer': 'Da! Îți trimitem raport foto și video complet al mașinii, plus raportul de verificare tehnică.'
  },
  en: {
    // Hero Section
    'hero.badge': 'Custom Car Sourcing from Europe',
    'hero.title': 'Car import',
    'hero.title.highlight': 'simple and safe.',
    'hero.subtitle': 'We find, verify and deliver the car you want from Europe.',
    'hero.cta.primary': 'Find My Car',
    'hero.cta.secondary': 'Cost Calculator',
    'hero.cta.tertiary': 'View Live Auctions',
    'hero.features.no_hidden_costs': 'No hidden costs',
    'hero.features.full_warranty': 'Full warranty',
    'hero.features.fast_delivery': 'Fast delivery',
    'hero.expert': 'Expert',
    'hero.expert.subtitle': 'Personalized Services',

    // International Auctions Section
    'international_auctions.title': 'Direct Access to International Auctions',
    'international_auctions.subtitle': 'We import from the world\'s largest auto markets to offer you the best prices and largest selection',
    'international_auctions.countries.title': 'Import Markets',
    'international_auctions.platforms.title': 'Partner Platforms',
    'international_auctions.benefits.title': 'Our Advantages',
    'international_auctions.benefits.better_prices': 'Prices 20-30% lower',
    'international_auctions.benefits.huge_selection': 'Selection of over 100,000 vehicles',
    'international_auctions.benefits.direct_access': 'Direct access to live auctions',
    'international_auctions.countries.usa': 'USA',
    'international_auctions.countries.eu': 'European Union',
    'international_auctions.cta': 'View Live Auctions',

    // How It Works Section
    'how_it_works.title': 'How It Works?',
    'how_it_works.subtitle': 'Our simple 4-step process to import your dream car',
    'how_it_works.step1.title': 'Consultation',
    'how_it_works.step1.description': 'We discuss your preferences and available budget',
    'how_it_works.step2.title': 'Search',
    'how_it_works.step2.description': 'We find the perfect car in our European network',
    'how_it_works.step3.title': 'Import',
    'how_it_works.step3.description': 'We handle all import formalities and transport',
    'how_it_works.step4.title': 'Delivery',
    'how_it_works.step4.description': 'We deliver the car directly to your address',

    // Why Choose Us Section
    'why_choose.title': 'Why Choose AutoMode?',
    'why_choose.subtitle': 'Your trusted partners for European car imports. We offer complete and transparent services to bring you the perfect car.',
    'why_choose.warranty.title': '12 Months Warranty',
    'why_choose.warranty.description': 'The most extensive warranty in Romania for imported cars with complete protection.',
    'why_choose.report.title': 'Complete Car Report',
    'why_choose.report.description': 'Detailed technical analysis and professional checks for every vehicle.',
    'why_choose.delivery.title': 'Home Delivery',
    'why_choose.delivery.description': 'Safe and insured transport directly to your address, without you having to travel.',
    'why_choose.registration.title': 'RAR Registration',
    'why_choose.registration.description': 'We handle all RAR formalities and deliver your car ready to drive.',

    // Featured Cars Section
    'featured_cars.title': 'Popular Cars',
    'featured_cars.subtitle': 'Discover the most sought-after models we have recently imported',
    'featured_cars.badge.premium': 'Premium',
    'featured_cars.badge.luxury': 'Luxury',
    'featured_cars.badge.performance': 'Performance',
    'featured_cars.details_button': 'Details',

    // Cost Estimator Section
    'cost_estimator.title': 'Calculate Costs Exactly',
    'cost_estimator.subtitle': 'Use our advanced calculator to get an accurate estimate of the costs for importing your car. Includes all taxes, transport and fees.',
    'cost_estimator.feature1': 'Calculator with 2 variants: Without VAT and With VAT',
    'cost_estimator.feature2': 'Automatic calculation of required advance (20%)',
    'cost_estimator.feature3': 'Real-time results, no surprises',
    'cost_estimator.cta': 'Cost Calculator',

    // Warranty Section
    'warranty.title': 'Complete 12 Months Warranty',
    'warranty.subtitle': 'Invest in your car with total confidence. Every imported vehicle comes with our extended warranty for your complete peace of mind.',
    'warranty.complete_protection.title': 'Complete Protection',
    'warranty.complete_protection.description': 'We cover all mechanical and electrical problems that may arise in the first year from import, without exceptions.',
    'warranty.quality_service.title': 'Quality Service',
    'warranty.quality_service.description': 'We collaborate with authorized services to ensure professional repairs and reliable maintenance.',
    'warranty.dedicated_support.title': 'Dedicated Support',
    'warranty.dedicated_support.description': 'Our team provides consultation and assistance throughout the warranty period for your peace of mind.',
    'warranty.what_includes.title': 'What Does Our Warranty Include?',
    'warranty.what_includes.mechanical': 'Main mechanical components',
    'warranty.what_includes.electrical': 'Electrical and electronic systems',
    'warranty.what_includes.safety': 'Safety and comfort elements',
    'warranty.what_includes.support': 'Technical support and consultation',
    'warranty.months': 'Months Warranty',
    'warranty.months_description': 'The most extensive warranty in the industry for imported cars',
    'warranty.questions.title': 'Questions About Warranty?',
    'warranty.questions.subtitle': 'Our team of specialists explains in detail all the benefits of the extended warranty and how it protects your investment.',
    'warranty.cta.primary': 'Find My Car',
    'warranty.cta.secondary': 'Ask Us',

    // Available Cars Section
    'cars.title': 'Available Cars',
    'cars.subtitle': 'Discover the premium cars from our stock and consignment listings',
    'cars.count': 'cars available',
    'cars.year': 'Year',
    'cars.mileage': 'Mileage',
    'cars.fuel': 'Fuel',
    'cars.engine': 'Engine',
    'cars.transmission': 'Transmission',
    'cars.price': 'Price',
    'cars.details': 'View Details',

    // Exclusivity Section
    'exclusivity.badge': 'Limited spots —',
    'exclusivity.title': 'We only accept a limited number of orders.',
    'exclusivity.subtitle': 'We work with a small number of clients because every order receives personal attention, from sourcing to delivery.',
    'exclusivity.reserved': 'Your spot has been reserved!',
    'exclusivity.contact_soon': 'We will contact you soon at',
    'exclusivity.email_placeholder': 'Your email address',
    'exclusivity.cta': 'Reserve your spot for free →',

    // FAQ Section
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Answers to the most common questions about our custom car sourcing service',
    'faq.q1.question': 'How does the custom car sourcing work?',
    'faq.q1.answer': 'You specify exactly the car you want (brand, model, color, features) through our platform. We search and purchase it from international auctions (OpenLane, Auto1), then bring it to Romania with all formalities handled.',
    'faq.q2.question': 'What auction platforms do you use?',
    'faq.q2.answer': 'We work with OpenLane.eu for car auctions and Auto1.com for the European market. These give us access to over 100,000 vehicles from live auctions.',
    'faq.q3.question': 'How much does it cost to import a custom-sourced car?',
    'faq.q3.answer': 'Use our calculator for an exact estimate. We include all costs: car price, transport, RAR registration, plus our 12-month warranty. No surprises!',
    'faq.q4.question': 'What warranty do you offer and what does it include?',
    'faq.q4.answer': 'We offer a 12-month warranty, the most extensive in Romania for imported cars. It covers mechanical components, electrical systems, safety elements, plus technical support and consultation.',
    'faq.q5.question': 'Do you handle RAR registration too?',
    'faq.q5.answer': 'Absolutely! Our all-inclusive service includes all RAR formalities. We deliver your car with plates mounted and ready to drive, plus ITP completed.',

    // Testimonials Section
    'testimonials.title': 'What Our Clients Say',
    'testimonials.subtitle': 'Real experiences of our satisfied clients',
    'testimonials.review1': 'Excellent service! They found exactly the BMW I was looking for and handled everything professionally.',
    'testimonials.review2': 'Transparent, fast and efficient. I save a lot compared to the local market and the car is in perfect condition.',
    'testimonials.review3': 'The Automode team helped me import my dream Mercedes. The process was simple and hassle-free.',

    // WhatsApp
    'whatsapp.tooltip': 'Write to us on WhatsApp',

    // Header Navigation
    'header.nav.calculator': 'Cost Calculator',
    'header.nav.order_car': 'Order Car',
    'header.nav.send_openlane': 'Send Link',
    'header.nav.masini_la_comanda': 'Order a Car',
    'header.nav.stoc': 'Stock',
    'header.nav.navigation': 'Navigation',
    'header.user.welcome': 'Welcome!',

    // Header User Menu
    'header.user.my_account': 'My Account',
    'header.user.sign_out': 'Sign Out',
    'header.user.sign_in': 'Sign In',
    'header.user.create_account': 'Create Account',
    'header.user.administrator': 'Administrator',

    // Breadcrumbs
    'breadcrumbs.home': 'Home',
    'breadcrumbs.masini_la_comanda': 'Order a Car',
    'breadcrumbs.calculator': 'Import Calculator',
    'breadcrumbs.stoc': 'Car Stock',
    'breadcrumbs.dashboard': 'Dashboard',
    'breadcrumbs.cereri': 'Requests',
    'breadcrumbs.analitice': 'Analytics',
    'breadcrumbs.confidentialitate': 'Privacy Policy',
    'breadcrumbs.cookies': 'Cookie Policy',
    'breadcrumbs.gdpr': 'GDPR',

    // Footer
    'footer.company_description': 'Your trusted partner for importing premium vehicles from Europe. We handle everything, from selection to delivery, turning your dream car into reality.',
    'footer.services': 'Services',
    'footer.order_car': 'Order Car',
    'footer.cost_calculator': 'Cost Calculator',
    'footer.legal': 'Legal',
    'footer.terms_conditions': 'Terms and Conditions',
    'footer.privacy_policy': 'Privacy Policy',
    'footer.cookies_policy': 'Cookies Policy',
    'footer.copyright': 'Automode SRL',

    // Dashboard Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.car_requests': 'Car Requests',
    'sidebar.calculator': 'Cost Calculator',
    'sidebar.contracts': 'Contracts',
    'sidebar.logout': 'Logout',

    // Dashboard Page
    'dashboard.welcome': 'Good day',
    'dashboard.subtitle': 'Welcome to your Automode dashboard',
    'dashboard.stats.active_requests': 'Active Requests',
    'dashboard.stats.offers_received': 'Offers Received',
    'dashboard.stats.contracts': 'Contracts',
    'dashboard.account_info': 'Account Information',
    'dashboard.account_info.name': 'Name',
    'dashboard.account_info.email': 'Email',
    'dashboard.account_info.phone': 'Phone',
    'dashboard.account_info.member_since': 'Member since',
    'dashboard.account_info.not_set': 'Not set',
    'dashboard.recent_activity': 'Recent Activity',
    'dashboard.recent_activity.contract': 'Contract',
    'dashboard.recent_activity.client': 'Client',
    'dashboard.recent_activity.contract_date': 'Contract date',
    'dashboard.recent_activity.created': 'Created',
    'dashboard.recent_activity.status.signed': 'Signed',
    'dashboard.recent_activity.status.draft': 'Draft',
    'dashboard.recent_activity.no_activity': 'No recent activity',
    'dashboard.recent_activity.contracts_appear_here': 'Your contracts will appear here',

    // Calculator Page
    'calculator.title': 'Import Cost Calculator',
    'calculator.subtitle': 'Calculate the exact costs for importing your car from Europe',

    // Contracts Page
    'contracts.title': 'My Contracts',
    'contracts.subtitle': 'View and manage your contracts',

    // Car Requests Page
    'car_requests.new_order': 'Order New Car',
    'car_requests.form_description': 'Complete the form to create a new request',
    'car_requests.year': 'Year',
    'car_requests.max_budget': 'Max budget',
    'car_requests.fuel_type': 'Fuel type',
    'car_requests.additional_requirements': 'Additional requirements',
    'car_requests.created_on': 'Created on',
    'car_requests.not_specified': 'Not specified',

    // Calculator Component
    'calc.title': 'Import Cost Calculator',
    'calc.tab.without_vat': 'Without VAT',
    'calc.tab.with_vat': 'With VAT',
    'calc.price_label': 'Car price (€)',
    'calc.price_placeholder': 'Enter car price',
    'calc.openlane_taxes': 'OpenLane Taxes',
    'calc.transport_label': 'Transport (€)',
    'calc.transport_placeholder': 'Enter transport cost',
    'calc.warranty': 'Warranty',
    'calc.commission': 'Commission',
    'calc.vat': 'VAT (21%)',
    'calc.total': 'Total',
    'calc.advance': 'Required advance (20%)',

    // Contracts Page Details
    'contracts.loading': 'Loading contracts...',
    'contracts.no_contracts': 'You have no available contracts',
    'contracts.status.draft': 'Draft',
    'contracts.status.signed': 'Signed',
    'contracts.status.sent_to_client': 'Sent to client',
    'contracts.status.signed_by_client': 'Signed by client',
    'contracts.status.archived': 'Archived',
    'contracts.status.cancelled': 'Cancelled',
    'contracts.view_contract': 'View Contract',
    'contracts.sign_contract': 'Sign Contract',
    'contracts.contract_number': 'Contract',
    'contracts.created': 'Created',
    'contracts.amount': 'Amount',

    // Car Selection Form
    'car_form.title': 'Select Your Desired Car',
    'car_form.subtitle': 'Fill in the details about the car you are looking for',
    'car_form.make_label': 'Make *',
    'car_form.make_placeholder': 'Select make...',
    'car_form.model_label': 'Model *',
    'car_form.model_placeholder': 'Select model...',
    'car_form.year_label': 'Year *',
    'car_form.year_placeholder': 'Select year...',
    'car_form.fuel_type_label': 'Fuel Type (optional)',
    'car_form.fuel_type_placeholder': 'Select fuel type...',
    'car_form.transmission_label': 'Transmission Type (optional)',
    'car_form.transmission_placeholder': 'Select transmission type...',
    'car_form.max_mileage_label': 'Max Mileage (optional)',
    'car_form.max_mileage_placeholder': 'e.g.: 150000',
    'car_form.max_mileage_hint': 'in kilometers',
    'car_form.budget_label': 'Budget (EUR) *',
    'car_form.budget_placeholder': 'e.g.: 25000',
    'car_form.features_label': 'Desired Features (optional)',
    'car_form.features_placeholder': 'Select features...',
    'car_form.additional_notes_label': 'Additional Notes (optional)',
    'car_form.additional_notes_placeholder': 'Additional details about the desired car, special preferences...',
    'car_form.submit_button': 'Send Request',
    'car_form.submitting_button': 'Sending...',

    // Car Features
    'car_features.leather': 'Leather interior',
    'car_features.sunroof': 'Sunroof',
    'car_features.navigation': 'Navigation system',
    'car_features.heated_seats': 'Heated seats',
    'car_features.cooled_seats': 'Cooled seats',
    'car_features.heated_steering': 'Heated steering wheel',
    'car_features.bluetooth': 'Bluetooth',
    'car_features.backup_camera': 'Backup camera',
    'car_features.360_camera': '360° camera',
    'car_features.cruise_control': 'Cruise control',
    'car_features.adaptive_cruise': 'Adaptive cruise control',
    'car_features.keyless': 'Keyless start',
    'car_features.keyless_entry': 'Keyless entry',
    'car_features.premium_audio': 'Premium audio system',
    'car_features.xenon': 'Xenon/LED headlights',
    'car_features.matrix_led': 'Matrix LED headlights',
    'car_features.parking_sensors': 'Parking sensors',
    'car_features.auto_park': 'Auto park',
    'car_features.climate_control': 'Auto climate control',
    'car_features.dual_zone_climate': 'Dual-zone climate',
    'car_features.tri_zone_climate': 'Tri-zone climate',
    'car_features.lane_assist': 'Lane assist',
    'car_features.blind_spot': 'Blind spot monitor',
    'car_features.collision_warning': 'Collision warning',
    'car_features.emergency_brake': 'Emergency braking',
    'car_features.traffic_sign': 'Traffic sign recognition',
    'car_features.wireless_charging': 'Wireless charging',
    'car_features.apple_carplay': 'Apple CarPlay',
    'car_features.android_auto': 'Android Auto',
    'car_features.heads_up_display': 'Head-up Display',
    'car_features.panoramic_roof': 'Panoramic roof',
    'car_features.electric_seats': 'Electric seats',
    'car_features.memory_seats': 'Memory seats',
    'car_features.massage_seats': 'Massage seats',
    'car_features.sport_suspension': 'Sport suspension',
    'car_features.air_suspension': 'Air suspension',
    'car_features.awd': 'All-wheel drive',
    'car_features.sport_mode': 'Driving modes',
    'car_features.start_stop': 'Start-Stop system',
    'car_features.eco_mode': 'Eco mode',
    'car_features.night_vision': 'Night vision',
    'car_features.ambient_lighting': 'Ambient lighting',

    // Fuel Types
    'fuel_types.benzina': 'Gasoline',
    'fuel_types.motorina': 'Diesel',
    'fuel_types.hybrid': 'Hybrid',
    'fuel_types.electric': 'Electric',
    'fuel_types.gpl': 'LPG',
    'fuel_types.cng': 'CNG',
    'fuel_types.mild_hybrid': 'Mild Hybrid',
    'fuel_types.plug_in_hybrid': 'Plug-in Hybrid',
    'fuel_types.hydrogen': 'Hydrogen',
    'fuel_types.ethanol': 'Ethanol',
    'fuel_types.lpg': 'LPG',
    'fuel_types.flex_fuel': 'Flex Fuel',
    'fuel_types.bi_fuel': 'Bi-Fuel',
    'fuel_types.range_extender': 'Range Extender',

    // Transmission Types
    'transmission.manuala': 'Manual',
    'transmission.automata': 'Automatic',
    'transmission.semiautomata': 'Semi-automatic',
    'transmission.cvt': 'CVT',
    'transmission.dsg': 'DSG',
    'transmission.tiptronic': 'Tiptronic',
    'transmission.multitronic': 'Multitronic',
    'transmission.s_tronic': 'S-Tronic',
    'transmission.pdk': 'PDK',
    'transmission.zf_8hp': 'ZF 8HP',
    'transmission.torque_converter': 'Torque Converter',
    'transmission.dual_clutch': 'Dual Clutch',
    'transmission.single_speed': 'Single Speed (Electric)',
    'transmission.e_cvt': 'e-CVT',
    'transmission.amt': 'AMT',
    'transmission.imt': 'iMT',

    // Validation Messages
    'validation.select_make': 'Please select make',
    'validation.select_model': 'Please select model',
    'validation.year_after_1985': 'Year must be after 1985',
    'validation.year_not_future': 'Year cannot be in the future',
    'validation.budget_min': 'Minimum budget is €1,000',
    'validation.budget_max': 'Maximum budget is €500,000',

    // Toast Messages
    'toast.login_required': 'You must be logged in to submit a request.',
    'toast.profile_error': 'Could not access profile information.',
    'toast.database_error': 'Database error',
    'toast.email_failed': 'Request was saved, but email notification failed.',
    'toast.request_success': 'Your request has been sent successfully! You will find it in the requests list.',
    'toast.general_error': 'An error occurred. Please try again.',

    // Consignatie Section
    'consignatie.title': 'Car Consignment',
    'consignatie.subtitle': 'We sell your car safely and at the best price',
    'consignatie.description': 'Put your car in our consignment and let us sell it for you. We handle the entire sales process, from promotion to transaction completion.',
    'consignatie.benefit1.title': 'Professional Evaluation',
    'consignatie.benefit1.description': 'We correctly evaluate your car and establish the best selling price on the market',
    'consignatie.benefit2.title': 'Complete Marketing',
    'consignatie.benefit2.description': 'We promote your car on all relevant platforms and in our network of buyers',
    'consignatie.benefit3.title': 'Complete Documentation',
    'consignatie.benefit3.description': 'We handle all the documents and formalities necessary for the sale',
    'consignatie.benefit4.title': 'Guaranteed Payment',
    'consignatie.benefit4.description': 'You receive the money immediately after sale, without risks or delays',
    'consignatie.cta': 'Put Car in Consignment',
    'consignatie.contact': 'Contact Us for Evaluation',

    // Progress Tracking
    'progress.title': 'Car Import Progress',
    'progress.stages_completed': '{{completed}} of {{total}} stages completed',
    'progress.percent_complete': '{{percent}}% complete',
    'progress.current_stage': 'Current stage: {{stage}}',
    'progress.notification_text': 'You will be notified when this stage is completed and we move to the next one.',
    'progress.stages.requested': 'Request Sent',
    'progress.stages.requested_desc': 'Your car import request has been submitted',
    'progress.stages.searching': 'Active Search',
    'progress.stages.searching_desc': 'We are actively searching for your desired vehicle',
    'progress.stages.found': 'Car Found',
    'progress.stages.found_desc': 'Perfect match found! Vehicle details will be shared',
    'progress.stages.auction_time': 'Auction Time',
    'progress.stages.auction_time_desc': 'Car is at auction - result will be communicated soon',
    'progress.stages.auction_won': 'Auction Won',
    'progress.stages.auction_won_desc': 'Congratulations! We won the auction for your car',
    'progress.stages.auction_lost': 'Purchase Failed (price exceeded)',
    'progress.stages.auction_lost_desc': 'Unfortunately the price exceeded the set budget',
    'progress.stages.purchase_failed': 'Purchase Failed (price exceeded)',
    'progress.stages.purchase_failed_desc': 'Unfortunately the price exceeded the set budget',
    'progress.stages.purchased': 'Purchased',
    'progress.stages.purchased_desc': 'Vehicle purchased! Payment confirmed and processed',
    'progress.stages.in_transit': 'In Transit',
    'progress.stages.in_transit_desc': 'Vehicle is being transported to Romania',
    'progress.stages.delivered': 'Delivered',
    'progress.stages.delivered_desc': 'Vehicle ready for pickup or home delivery',
    'progress.status.in_progress': 'In Progress',
    'progress.status.completed': 'Completed',
    'progress.status.delayed': 'Delayed',
    'progress.date.completed': 'Completed: {{date}}',
    'progress.date.estimated': 'Estimated: {{date}}',
    'progress.date.today': 'Today',
    'progress.date.tomorrow': 'Tomorrow',
    'progress.date.in_days': 'in {{days}} days',
    'progress.date.yesterday': 'Yesterday',
    'progress.date.days_ago': '{{days}} days ago',
    'progress.last_updated': 'Last updated',

    // Notifications
    'notifications.title': 'Notifications',
    'notifications.mark_all_read': 'Mark all as read',
    'notifications.no_notifications': 'No new notifications',
    'notifications.no_notifications_desc': 'We will show you updates about your requests here.',

    // Onboarding
    'onboarding.welcome': 'Welcome',
    'onboarding.skip': 'Skip guide',
    'onboarding.next': 'Next',
    'onboarding.previous': 'Previous',
    'onboarding.finish': 'Let\'s get started!',
    'onboarding.step_of': 'Step {{current}} of {{total}}',

    // Stoc Page
    'stoc.title': 'Our Stock',
    'stoc.subtitle': 'Discover the cars available in our stock. All vehicles are verified and ready for delivery.',
    'stoc.empty.title': 'No cars in stock at the moment',
    'stoc.empty.subtitle': 'Check back soon for new vehicles added.',
    'stoc.spec.year': 'Year',
    'stoc.spec.km': 'Km',
    'stoc.spec.fuel': 'Fuel',
    'stoc.spec.engine': 'Engine',
    'stoc.spec.transmission': 'Transmission',
    'stoc.spec.equipment': 'Trim',
    'stoc.price': 'Price',
    'stoc.view_details': 'View Details',
    'stoc.banner.text': "Can't find what you're looking for? We order any car from Europe in 2-3 weeks.",
    'stoc.banner.cta': 'I Want My Car',

    // Stoc Detail Page
    'stoc_detail.back': 'Back to Stock',
    'stoc_detail.warranty.title': 'Warranty',
    'stoc_detail.warranty.months': 'Months',
    'stoc_detail.warranty.description': 'Full protection included',
    'stoc_detail.warranty.certified': 'CERTIFIED',
    'stoc_detail.spec.year': 'Year',
    'stoc_detail.spec.km': 'Mileage',
    'stoc_detail.spec.fuel': 'Fuel',
    'stoc_detail.spec.engine': 'Engine',
    'stoc_detail.spec.power': 'Power',
    'stoc_detail.spec.transmission': 'Transmission',
    'stoc_detail.spec.co2': 'CO2 Emissions',
    'stoc_detail.spec.equipment': 'Trim',
    'stoc_detail.spec.vin': 'VIN',
    'stoc_detail.spec.registration': 'Registration',
    'stoc_detail.price': 'Price:',
    'stoc_detail.contact': 'Contact Us: 0770852489',
    'stoc_detail.features': 'Features',
    'stoc_detail.report.view': 'View CarVertical Report',
    'stoc_detail.report.title': 'CarVertical Report',
    'stoc_detail.report.short': 'CV Report',
    'stoc_detail.report.download': 'Download',
    'stoc_detail.error': 'Car not found',

    // Calculator Page
    'calc_page.title': 'Cost Calculator',
    'calc_page.subtitle': 'Calculate the costs for importing your car',
    'calc_page.tab.without_vat': 'Without VAT',
    'calc_page.tab.with_vat': 'With VAT',
    'calc_page.price_label': 'Price (EUR)',
    'calc_page.price_placeholder': 'Enter price',
    'calc_page.auction_taxes_label': 'Auction Taxes (EUR)',
    'calc_page.auction_taxes_hint': 'Price is approximate as it varies by country',
    'calc_page.vat_label': 'VAT 21% (EUR)',
    'calc_page.vat_hint': 'VAT is calculated based on price + auction taxes (21%)',
    'calc_page.transport_label': 'Transport (EUR)',
    'calc_page.commission_label': 'Commission (EUR)',
    'calc_page.total': 'Total:',
    'calc_page.note_prefix': 'Note:',
    'calc_page.advance_note': 'If you wish to proceed, our advance payment is 20% of the base price.',
    'calc_page.advance_label': 'Required advance (20%):',
    'calc_page.cta.title': 'Ready to Buy Your Dream Car?',
    'calc_page.cta.text': 'Now that you know the exact costs, request your desired car and start the order process. Our team will guide you step by step to the perfect car.',
    'calc_page.cta.button': 'I want this car.',
    'calc_page.cta.benefits': '✓ Free account • ✓ No obligations • ✓ Personalized support',

    // Car Order Form (multi-step)
    'car_order_form.step1.label': 'Contact',
    'car_order_form.step2.label': 'Preferences',
    'car_order_form.step3.label': 'Details',
    'car_order_form.step4.label': 'Confirmation',
    'car_order_form.full_name_label': 'Full Name *',
    'car_order_form.phone_label': 'Phone *',
    'car_order_form.brand_label': 'Brand *',
    'car_order_form.brand_placeholder': 'Select brand',
    'car_order_form.other_brand': 'Other brand',
    'car_order_form.custom_brand_label': 'Specify Brand *',
    'car_order_form.custom_brand_placeholder': 'e.g.: Dacia, Subaru, Mitsubishi',
    'car_order_form.model_label': 'Model *',
    'car_order_form.model_placeholder': 'e.g.: 5 Series, E-Class, A6',
    'car_order_form.year_min_label': 'Year (Minimum) *',
    'car_order_form.year_max_label': 'Year (Maximum)',
    'car_order_form.year_placeholder': 'Select year',
    'car_order_form.fuel_label': 'Fuel Type',
    'car_order_form.fuel_placeholder': 'Select type',
    'car_order_form.transmission_label': 'Transmission',
    'car_order_form.transmission_placeholder': 'Select type',
    'car_order_form.fuel.benzina': 'Gasoline',
    'car_order_form.fuel.diesel': 'Diesel',
    'car_order_form.fuel.hibrid': 'Hybrid',
    'car_order_form.fuel.electric': 'Electric',
    'car_order_form.fuel.hibrid_plugin': 'Plug-in Hybrid',
    'car_order_form.fuel.any': 'Any',
    'car_order_form.transmission.automatic': 'Automatic',
    'car_order_form.transmission.manual': 'Manual',
    'car_order_form.transmission.any': 'Any',
    'car_order_form.budget_min_label': 'Min Budget (EUR) *',
    'car_order_form.budget_max_label': 'Max Budget (EUR) *',
    'car_order_form.mileage_label': 'Max Mileage (km)',
    'car_order_form.color_label': 'Preferred Color',
    'car_order_form.color_placeholder': 'e.g.: Black, White, Grey',
    'car_order_form.requirements_label': 'Additional Requirements',
    'car_order_form.requirements_placeholder': 'Mention any other requirements or preferences (e.g.: sport package, leather interior, premium audio, etc.)',
    'car_order_form.review_title': 'Review Your Details:',
    'car_order_form.review.name': 'Name:',
    'car_order_form.review.email': 'Email:',
    'car_order_form.review.phone': 'Phone:',
    'car_order_form.review.brand': 'Brand:',
    'car_order_form.review.model': 'Model:',
    'car_order_form.review.year': 'Year:',
    'car_order_form.review.budget': 'Budget:',
    'car_order_form.review.fuel': 'Fuel:',
    'car_order_form.review.transmission': 'Transmission:',
    'car_order_form.terms_prefix': 'I accept the ',
    'car_order_form.terms_link': 'Privacy Policy',
    'car_order_form.terms_suffix': ' and agree for AutoMode to contact me with personalized offers for the desired car.',
    'car_order_form.back': 'Back',
    'car_order_form.continue': 'Continue',
    'car_order_form.submit': 'Send Request',
    'car_order_form.submitting': 'Sending...',
    'car_order_form.success.title': 'Thank you for your order!',
    'car_order_form.success.message': 'We have received your request and our team will contact you soon with personalized offers.',
    'car_order_form.success.back_home': 'Back to Home Page',
    'car_order_form.error': 'An error occurred. Please try again.',

    // Masini la Comanda Page
    'masini_comanda.title': 'Tell us what car you want. We find it.',
    'masini_comanda.subtitle': 'Fill in 2 minutes — our team contacts you within 24 hours with concrete options.',
    'masini_comanda.cta.title': 'Have Questions?',
    'masini_comanda.cta.text': 'Our team is here to help you with any questions. Contact us on WhatsApp for a free consultation.',
    'masini_comanda.cta.button': 'WhatsApp',
    'masini_comanda.faq.title': 'Frequently Asked Questions',
    'masini_comanda.faq.q1.question': 'How long does the import process take?',
    'masini_comanda.faq.q1.answer': 'From the advance payment to delivery at your door, it takes an average of 2-3 weeks. This includes finding the right car, technical inspection, and transport.',
    'masini_comanda.faq.q2.question': 'What advance payment is required?',
    'masini_comanda.faq.q2.answer': 'We require a 20% advance of the total price to start the auction process. The remaining amount is paid within 48 hours of winning the auction.',
    'masini_comanda.faq.q3.question': 'What does the 12-month warranty include?',
    'masini_comanda.faq.q3.answer': 'The warranty covers all major mechanical and electrical components: engine, transmission, braking system, suspension, electrical system and electronics.',
    'masini_comanda.faq.q4.question': 'Can I see the car before buying?',
    'masini_comanda.faq.q4.answer': 'Yes! We send you a complete photo and video report of the car, plus the technical inspection report.'
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('ro')

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && (savedLanguage === 'ro' || savedLanguage === 'en')) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (newLanguage: Language) => {
    setLanguage(newLanguage)
    localStorage.setItem('language', newLanguage)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}